runtime: nodejs18
service: bicewellness-dev
# prettier-ignore


env_variables:
  NODE_ENV: dev
  DB_HOST: /cloudsql/peak-vortex-396916:us-east1:fi-db-mysql-prod
  
handlers:
- url: /.*
  script: "auto"
